### ISSUE TITLE
cems error message

### ISSUE THREAD

**Issue by backslashpaige** [drofphilosophe/USElecData#29]
[terminal_output.pdf](https://github.com/drofphilosophe/USElecData/files/10582609/terminal_output.pdf)

**Comment by backslashpaige** [comment]
[terminal_output_cems.pdf](https://github.com/drofphilosophe/USElecData/files/10582617/terminal_output_cems.pdf)

**Comment by drofphilosophe** [comment]
`FacilityInfo.py` Script fails with an HTTPError when you attempt to download a facility file that does not yet exist. E.g., the file for the current year when no hourly data for that year are yet available. Output below
`Getting Facility data for 2023
        Downloading
Traceback (most recent call last):
  File "C:\Users\archs\Documents\GitHub\Data\USElecData\src\EPA-CEMS\downloadFacilityInfo.py", line 117, in <module>
    with urllib.request.urlopen(req,context=ctx) as resp :
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\archs\anaconda3\envs\USElecData\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\archs\anaconda3\envs\USElecData\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\archs\anaconda3\envs\USElecData\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\archs\anaconda3\envs\USElecData\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\archs\anaconda3\envs\USElecData\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\archs\anaconda3\envs\USElecData\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

----- End Python script src\EPA-CEMS\downloadFacilityInfo.py -----`
